/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The location of the viewer of the live stream.
*/
export class LiveStreamSessionLocation {
    /**
    * The country of the viewer of the live stream.
    */
    'country'?: string;
    /**
    * The city of the viewer of the live stream.
    */
    'city'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "country",
            "baseName": "country",
            "type": "string",
            "format": ""
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LiveStreamSessionLocation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

