/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LiveStreamAssets } from './LiveStreamAssets';

export class LiveStream {
    /**
    * The unique identifier for the live stream. Live stream IDs begin with \"li.\"
    */
    'liveStreamId'?: string;
    /**
    * The name of your live stream.
    */
    'name'?: string;
    /**
    * The unique, private stream key that you use to begin streaming.
    */
    'streamKey'?: string;
    /**
    * Whether you are recording or not.
    */
    'record'?: boolean;
    /**
    * BETA FEATURE Please limit all public = false (\"private\") livestreams to 3,000 users. Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view.
    */
    '_public'?: boolean;
    'assets'?: LiveStreamAssets;
    /**
    * The unique identifier for the player.
    */
    'playerId'?: string;
    /**
    * Whether or not you are broadcasting the live video you recorded for others to see. True means you are broadcasting to viewers, false means you are not.
    */
    'broadcasting'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "liveStreamId",
            "baseName": "liveStreamId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "streamKey",
            "baseName": "streamKey",
            "type": "string",
            "format": ""
        },
        {
            "name": "record",
            "baseName": "record",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "LiveStreamAssets",
            "format": ""
        },
        {
            "name": "playerId",
            "baseName": "playerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "broadcasting",
            "baseName": "broadcasting",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LiveStream.attributeTypeMap;
    }
    
    public constructor() {
    }
}

