/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class LiveStreamSessionSession {
    /**
    * A unique identifier for your session. You can use this to track what happens during a specific session.
    */
    'sessionId'?: string;
    /**
    * When the session started, with the date and time presented in ISO-8601 format.
    */
    'loadedAt'?: Date;
    /**
    * When the session ended, with the date and time presented in ISO-8601 format.
    */
    'endedAt'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sessionId",
            "baseName": "sessionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "loadedAt",
            "baseName": "loadedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endedAt",
            "baseName": "endedAt",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return LiveStreamSessionSession.attributeTypeMap;
    }
    
    public constructor() {
    }
}

