/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class LiveStreamUpdatePayload {
    /**
    * The name you want to use for your live stream.
    */
    'name'?: string;
    /**
    * BETA FEATURE Please limit all public = false (\"private\") livestreams to 3,000 users. Whether your video can be viewed by everyone, or requires authentication to see it. A setting of false will require a unique token for each view.
    */
    '_public'?: boolean;
    /**
    * Use this to indicate whether you want the recording on or off. On is true, off is false.
    */
    'record'?: boolean;
    /**
    * The unique ID for the player associated with a live stream that you want to update.
    */
    'playerId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "record",
            "baseName": "record",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "playerId",
            "baseName": "playerId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LiveStreamUpdatePayload.attributeTypeMap;
    }
    
    public constructor() {
    }
}

