/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* What type of device the user is on when in the live stream session.
*/
export class LiveStreamSessionDevice {
    /**
    * What the type is like desktop, laptop, mobile.
    */
    'type'?: string;
    /**
    * If known, what the brand of the device is, like Apple, Dell, etc.
    */
    'vendor'?: string;
    /**
    * The specific model of the device, if known.
    */
    'model'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "vendor",
            "baseName": "vendor",
            "type": "string",
            "format": ""
        },
        {
            "name": "model",
            "baseName": "model",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LiveStreamSessionDevice.attributeTypeMap;
    }
    
    public constructor() {
    }
}

