/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlayerAllOfAssets } from './PlayerAllOfAssets';

export class PlayerAllOf {
    'playerId'?: string;
    /**
    * When the player was created, presented in ISO-8601 format.
    */
    'createdAt'?: Date;
    /**
    * When the player was last updated, presented in ISO-8601 format.
    */
    'updatedAt'?: Date;
    /**
    * Deprecated
    */
    'shapeMargin'?: number;
    /**
    * Deprecated
    */
    'shapeRadius'?: number;
    /**
    * Deprecated
    */
    'shapeAspect'?: string;
    /**
    * Deprecated
    */
    'shapeBackgroundTop'?: string;
    /**
    * Deprecated
    */
    'shapeBackgroundBottom'?: string;
    /**
    * Deprecated
    */
    'linkActive'?: string;
    'assets'?: PlayerAllOfAssets;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playerId",
            "baseName": "playerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "shapeMargin",
            "baseName": "shapeMargin",
            "type": "number",
            "format": ""
        },
        {
            "name": "shapeRadius",
            "baseName": "shapeRadius",
            "type": "number",
            "format": ""
        },
        {
            "name": "shapeAspect",
            "baseName": "shapeAspect",
            "type": "string",
            "format": ""
        },
        {
            "name": "shapeBackgroundTop",
            "baseName": "shapeBackgroundTop",
            "type": "string",
            "format": ""
        },
        {
            "name": "shapeBackgroundBottom",
            "baseName": "shapeBackgroundBottom",
            "type": "string",
            "format": ""
        },
        {
            "name": "linkActive",
            "baseName": "linkActive",
            "type": "string",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "PlayerAllOfAssets",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerAllOf.attributeTypeMap;
    }
    
    public constructor() {
    }
}

