/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class TokenCreatePayload {
    /**
    * Time in seconds that the token will be active. A value of 0 means that the token has no exipration date. The default is to have no expiration.
    */
    'ttl'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ttl",
            "baseName": "ttl",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TokenCreatePayload.attributeTypeMap;
    }
    
    public constructor() {
    }
}

