/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BytesRange } from './BytesRange';

/**
* Details about the capturing, transferring, and storing of your video for use immediately or in the future.
*/
export class VideoStatusIngest {
    /**
    * There are three possible ingest statuses. missing - you are missing information required to ingest the video. uploading - the video is in the process of being uploaded. uploaded - the video is ready for use.
    */
    'status'?: VideoStatusIngestStatusEnum;
    /**
    * The size of your file in bytes.
    */
    'filesize'?: number;
    /**
    * The total number of bytes received, listed for each chunk of the upload.
    */
    'receivedBytes'?: Array<BytesRange>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "VideoStatusIngestStatusEnum",
            "format": ""
        },
        {
            "name": "filesize",
            "baseName": "filesize",
            "type": "number",
            "format": ""
        },
        {
            "name": "receivedBytes",
            "baseName": "receivedBytes",
            "type": "Array<BytesRange>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoStatusIngest.attributeTypeMap;
    }
    
    public constructor() {
    }
}


export type VideoStatusIngestStatusEnum = "missing" | "uploading" | "uploaded" ;

