/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoSessionClient } from './VideoSessionClient';
import { VideoSessionDevice } from './VideoSessionDevice';
import { VideoSessionLocation } from './VideoSessionLocation';
import { VideoSessionOs } from './VideoSessionOs';
import { VideoSessionReferrer } from './VideoSessionReferrer';
import { VideoSessionSession } from './VideoSessionSession';

export class VideoSession {
    'session'?: VideoSessionSession;
    'location'?: VideoSessionLocation;
    'referrer'?: VideoSessionReferrer;
    'device'?: VideoSessionDevice;
    'os'?: VideoSessionOs;
    'client'?: VideoSessionClient;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "session",
            "baseName": "session",
            "type": "VideoSessionSession",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "VideoSessionLocation",
            "format": ""
        },
        {
            "name": "referrer",
            "baseName": "referrer",
            "type": "VideoSessionReferrer",
            "format": ""
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "VideoSessionDevice",
            "format": ""
        },
        {
            "name": "os",
            "baseName": "os",
            "type": "VideoSessionOs",
            "format": ""
        },
        {
            "name": "client",
            "baseName": "client",
            "type": "VideoSessionClient",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoSession.attributeTypeMap;
    }
    
    public constructor() {
    }
}

