/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoStatusEncoding } from './VideoStatusEncoding';
import { VideoStatusIngest } from './VideoStatusIngest';

export class VideoStatus {
    'ingest'?: VideoStatusIngest;
    'encoding'?: VideoStatusEncoding;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ingest",
            "baseName": "ingest",
            "type": "VideoStatusIngest",
            "format": ""
        },
        {
            "name": "encoding",
            "baseName": "encoding",
            "type": "VideoStatusEncoding",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoStatus.attributeTypeMap;
    }
    
    public constructor() {
    }
}

