/**
 * api.video
 * api.video is an API that encodes on the go to facilitate immediate playback, enhancing viewer streaming experiences across multiple devices and platforms. You can stream live or on-demand online videos within minutes.
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Quality } from './Quality';
import { VideoStatusEncodingMetadata } from './VideoStatusEncodingMetadata';

export class VideoStatusEncoding {
    /**
    * Whether the video is playable or not.
    */
    'playable'?: boolean;
    /**
    * Available qualities the video can be viewed in.
    */
    'qualities'?: Array<Quality>;
    'metadata'?: VideoStatusEncodingMetadata;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playable",
            "baseName": "playable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "qualities",
            "baseName": "qualities",
            "type": "Array<Quality>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "VideoStatusEncodingMetadata",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoStatusEncoding.attributeTypeMap;
    }
    
    public constructor() {
    }
}

